//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiRest.SRIntegracion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRIntegracion.IIntegracionService")]
    public interface IIntegracionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegracionService/ReniectExisteDNI", ReplyAction="http://tempuri.org/IIntegracionService/ReniectExisteDNIResponse")]
        bool ReniectExisteDNI(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegracionService/ReniectExisteDNI", ReplyAction="http://tempuri.org/IIntegracionService/ReniectExisteDNIResponse")]
        System.Threading.Tasks.Task<bool> ReniectExisteDNIAsync(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegracionService/InfocorpHistorial", ReplyAction="http://tempuri.org/IIntegracionService/InfocorpHistorialResponse")]
        UPC.BE.InfocorpData InfocorpHistorial(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegracionService/InfocorpHistorial", ReplyAction="http://tempuri.org/IIntegracionService/InfocorpHistorialResponse")]
        System.Threading.Tasks.Task<UPC.BE.InfocorpData> InfocorpHistorialAsync(string dni);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIntegracionServiceChannel : ApiRest.SRIntegracion.IIntegracionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IntegracionServiceClient : System.ServiceModel.ClientBase<ApiRest.SRIntegracion.IIntegracionService>, ApiRest.SRIntegracion.IIntegracionService {
        
        public IntegracionServiceClient() {
        }
        
        public IntegracionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IntegracionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegracionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegracionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ReniectExisteDNI(string dni) {
            return base.Channel.ReniectExisteDNI(dni);
        }
        
        public System.Threading.Tasks.Task<bool> ReniectExisteDNIAsync(string dni) {
            return base.Channel.ReniectExisteDNIAsync(dni);
        }
        
        public UPC.BE.InfocorpData InfocorpHistorial(string dni) {
            return base.Channel.InfocorpHistorial(dni);
        }
        
        public System.Threading.Tasks.Task<UPC.BE.InfocorpData> InfocorpHistorialAsync(string dni) {
            return base.Channel.InfocorpHistorialAsync(dni);
        }
    }
}
